# Set up the basic structure design for the production code.

FROM node:12-alpine

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin

WORKDIR /home/node/.npm-global
RUN chown -R node:node /home/node/.npm-global

WORKDIR /home/node/app
RUN chown -R node:node /home/node/app

USER node
