FROM node:12-alpine

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin

WORKDIR /home/node/.npm-global
RUN chown -R node:node /home/node/.npm-global

WORKDIR /home/node/workbench
RUN chown -R node:node /home/node/workbench

USER node
