# Deploy new db schema to prisma. This is a one time only command.
# To avoid having to install prisma on production, we'll use this image to
# run it once, and throw away that container.

# Using image instead of sharing volumes due to Jenkins running on docker,
# setting up the path would stop making this infrastructure design agnostic.

FROM rdok/prisma-cli:latest

COPY --chown=node:node . /home/node/app

WORKDIR /home/node/app
RUN chown -R node:node /home/node/app

