# This mean to be used for developer needs.
# For example, the `jest --watch` has the git dependency, which is installed
# below.

FROM rdok/graphql-blog-api:infrastructure

USER root

RUN apk add --no-cache git

USER node
