FROM rdok/prisma-cli:latest

COPY --chown=node:node . /home/node/app

WORKDIR /home/node/app
RUN chown -R node:node /home/node/app

# Using image instead of sharing volumes due to Jenkins running on docker,
# setting up the path would stop making this infrastructure design agnostic.
