version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
  prisma:
    ports:
      - "127.0.0.1:4466:4466"

networks:
  default:
    external:
      name: nginx-proxy