version: "3.7"

services:

  api:
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
      - VIRTUAL_PORT
    ports:
      - "${VIRTUAL_PORT}:${VIRTUAL_PORT}"

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
