version: "3.7"

services:
  api:

    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL

  prisma:
    # https://github.com/prisma/prisma/issues/2692#issuecomment-446935094
    network_mode: "host"

networks:
  default:
    external:
      name: nginx-proxy