version: "3.7"

services:
  api:
    volumes:
      - ".:/app"
      - "${DEV_NPM_CACHE}:/root/.npm"
    environment:
      - VIRTUAL_HOST

  db:
    ports:
      - "5432:5432"

  prisma:
    ports:
      - "4466:4466"