version: "3.7"

services:
  api:
    volumes:
      - ".:/app"
      - "${DEV_NPM_CACHE}:/root/.npm"
    ports:
      - "${VIRTUAL_PORT}:${VIRTUAL_PORT}"
    command: tail -f /dev/null
    working_dir: /app

  db:
    ports:
      - "5432:5432"

  prisma:
    ports:
      - "4466:4466"