version: "3.7"

services:

  api:
    environment:
      - POSTGRES_PASSWORD
      - NODE_ENV
      - VIRTUAL_PORT
      - GRAPHQL_BLOG_API_PRISMA_SECRET
    depends_on:
      - db
      - prisma
    networks:
      - backend
    command: sh -c "
      ./docker/wait-for-it.sh 'prisma:4466'
      && prisma deploy
      && npm run get-schema
      && npm run ${NODE_ENV}
      "

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - backend

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    networks:
      - backend
    depends_on:
      - db
    expose:
      - "4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: db
            database: postgres
            # schema: public
            user: postgres
            password: "$POSTGRES_PASSWORD"
            ssl: false
            rawAccess: true
            port: "5432"
            migrations: true


volumes:
  db:

networks:
  backend:
    driver: bridge
