version: "3.7"

services:
  api:
    build:
      args:
        environment: "--production"
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    networks:
      - frontend

networks:
  frontend:
    external:
      name: nginx-proxy
