version: "3.7"

services:

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
      args:
        environment: "production"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    ports:
      - "${VIRTUAL_PORT}"
    networks:
      - frontend

networks:
  frontend:
    external:
      name: nginx-proxy
