version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.infrastructure
    volumes:
      - ".:/home/node/app"
      - "${DEV_NPM_CACHE}:/home/node/.npm"
      - "${DEV_NPM_GLOBAL_CACHE}:/home/node/.npm-global"
    ports:
      - "${VIRTUAL_PORT}:${VIRTUAL_PORT}"
    command: sh -c "
      npm install -g prisma
      && npm install
      && ./docker/wait-for-it.sh 'prisma:4466'
      && prisma deploy
      && npm run get-schema
      && npm run ${NODE_ENV}
      "

  db:
    ports:
      - "5432:5432"

  prisma:
    ports:
      - "4466:4466"