#!/bin/sh
set -e

POSTGRES="psql --username ${POSTGRES_USER}"

echo "Creating database: ${DB_NAME}"
$POSTGRES <<EOSQL
CREATE DATABASE ${DB_NAME} OWNER ${POSTGRES_USER};
EOSQL

echo "Creating database: ${DB_NAME_TEST}"
$POSTGRES <<EOSQL
CREATE DATABASE ${DB_NAME_TEST} OWNER ${POSTGRES_USER};
EOSQL
